version: '2'

volumes:
  geth_rinkeby: {}

services:
  geth:
    image: aqt01/geth-rinkeby-docker
    build: .
    expose:
      - "8545"
      - "8546"
    volumes:                                                                 
      - geth_rinkeby:/.rinkeby
    environment:
      GETH_ALLOW_EXTERNAL_DOMAIN: "0.0.0.0"
      GETH_ENVIRONMENT: ${GETH_ENVIRONMENT} # SUPPORTED [prod, test]
      GETH_BOOTNODE_URL: ${GETH_BOOTNODE_URL} 
