version: '2'

volumes:
  geth_rinkeby: {}

services:
  geth-rinkeby:
    image: aqt01/geth:rinkeby
    build:
      context: .
      dockerfile: Dockerfile.rinkeby
    expose:
      - "8545"
      - "8546"
    volumes:                                                                 
      - geth_rinkeby:/.rinkeby
    environment:
      GETH_ALLOW_EXTERNAL_DOMAIN: "0.0.0.0"
      GETH_ENVIRONMENT: ${GETH_ENVIRONMENT} # SUPPORTED [prod, test]
      GETH_BOOTNODE_URL: ${GETH_BOOTNODE_URL} 


  geth-mainnet:
    image: aqt01/geth:mainnet
    build:
      context: .
      dockerfile: Dockerfile.mainnet
    expose:
      - "8545"
      - "8546"
    volumes:                                                                 
      - geth_rinkeby:/.rinkeby
    environment:
      GETH_ALLOW_EXTERNAL_DOMAIN: "0.0.0.0"
      GETH_ENVIRONMENT: ${GETH_ENVIRONMENT} # SUPPORTED [prod, test]
      GETH_BOOTNODE_URL: ${GETH_BOOTNODE_URL} 
